# Spectra config file (bundled; v{SPECTRA_CURRENT_VERSION})


# Configuration for Spectra
# -------------------------
[service]

# Determines the place where Spectra stores its data.
data_dir = "data"

# The key for encrypting cookies. The value below was generated on the first run
# of `Spectra init`, do not touch it unless you know what you are doing. (Users'
# sessions will be invalidated if you change this key.)
cookie_key = "{SPECTRA_COOKIE_KEY}"

# The time to refresh the database, i.e. to mark expired items as unavailable
# and remove items that are no longer needed. Note that this should be a cron
# expression, otherwise Spectra would fail to launch.
refresh_time = "0 0 4 * * ?"

# The domain name where the website is deployed.
domain = "https://example.com"

# The IP address on which the service listens.
host = "127.0.0.1"

# The port on which the service listens.
port = 3000


# Configuration for Cloudflare Turnstile
# --------------------------------------
[turnstile]

# Whether to enable Cloudflare Turnstile.
# WARNING: Disabling this will prevent anonymous item creation.
enabled = true

# Note: default values are for testing; you should replace them with your own.
# Get one at https://dash.cloudflare.com/?to=/:account/turnstile
site_key = "1x00000000000000000000AA"
secret_key = "1x0000000000000000000000000000000AA"
